# DATAFRAME CONVERSION

### Library Import

In [16]:
#Basic operations and visualization
import pandas as pd 
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline

#Column transformation
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

### Dataset Import

In [19]:
DF = pd.read_csv('../data/Loan_test_set.csv', skiprows = 1)
loan.shape
loan.head()

/Users/gonzalocarretero/opt/anaconda3/envs/models/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (0,118,145,146,147) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id        member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title        emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url                                                desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line fico_range_low fico_range_high inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d last_fico_range_high last_fico_range_low collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_fico_range_low sec_app_fico_range_high sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount disbursement_method debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
104046719 NaN       14000     14000       14000            36 months  15.99%  492.13      C     C5        Project Leader   10+ years  MORTGAGE       82000      Source Verified     Mar-2017 Current     n          https://lendingclub.com/browse/loanDetail.actio... NaN  credit_card        Credit card refinancing 672xx    KS         31.07 0           May-1996         725            729             0              NaN                    NaN                    18       0       69578     63.2%      31        w                   11438.26  11438.26      3912.17     3912.17         2561.74         1350.43       0.0                0.0        0.0                     Dec-2017     492.13          Jan-2018     Dec-2017           714                  710                 0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            202617      0           3           0           1           22                 34430        57      0           2           13686      61       110037           0      9           0            3                    11257       29762          63.4    0                        0           140                250                  13                    13             6        13                   NaN                      13                    NaN                            0                     7              9               8           13        4         14            21            9                   18       0                0            0                  0                  100            25               0                    0         286204          104008            81400          60167                      NaN             NaN                    NaN                     NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Cash                N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
104048967 NaN       5000      5000        5000             36 months  25.49%  200.1       E     E4        Pilot            10+ years  MORTGAGE       215000     Source Verified     Mar-2017 Current     n          https://lendingclub.com/browse/loanDetail.actio... NaN  debt_consolidation Debt consolidation      067xx    CT         6.06  0           Jan-2004         765            769             4              NaN                    NaN                    11       0       8678      18.8%      16        f                   4190.59   4190.59       1586.64     1586.64         809.41          777.23        0.0                0.0        0.0                     Dec-2017     200.1           Jan-2018     Dec-2017           779                  775                 0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            44754       1           3           2           4           7                  35832        68      2           2           8659       27       46200            2      0           6            6                    4069        37522          18.8    0                        0           83                 87                   5                     5              0        5                    NaN                      0                     NaN                            0                     2              2               7           8         7         7             8             2                   11       0                0            0                  4                  100            0                0                    0         100763          44754             46200          49814                      NaN             NaN                    NaN                     NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Cash                N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
104028593 NaN       4600      4600        4600             36 months  11.39%  151.45      B     B3        cable technician 4 years    RENT           44470      Not Verified        Mar-2017 Current     n          https://lendingclub.com/browse/loanDetail.actio... NaN  credit_card        Credit card refinancing 066xx    CT         13.43 0           Dec-2003         770            774             1              NaN                    NaN                    7        0       5400      19.1%      11        w                   3708.50   3708.50       1205.78     1205.78         891.50          314.28        0.0                0.0        0.0                     Dec-2017     151.45          Jan-2018     Dec-2017           769                  765                 0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            9625        1           1           0           1           22                 4225         36      2           4           4670       24       28300            0      0           1            5                    1375        9610           33.7    0                        0           77                 159                  1                     1              0        7                    NaN                      1                     NaN                            0                     2              3               3           4         2         6             9             3                   7        0                0            0                  2                  100            0                0                    0         40000           9625              14500          11700                      NaN             NaN                    NaN                     NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Cash                N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
104046702 NaN       14000     14000       14000            60 months  12.74%  316.69      C     C1        Specialty Sales  4 years    OWN            40000      Not Verified        Mar-2017 Current     n          https://lendingclub.com/browse/loanDetail.actio... NaN  credit_card        Credit card refinancing 926xx    CA         17.48 0           Feb-1974         715            719             0              NaN                    NaN                    10       0       25787     46.2%      23        w                   12604.51  12604.51      2585.32     2585.32         1395.49         1189.83       0.0                0.0        0.0                     Dec-2017     316.69          Jan-2018     Dec-2017           714                  710                 0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            25787       2           0           0           0           129                0            NaN     5           7           8549       46       55800            0      3           0            7                    2579        27153          48.3    0                        0           129                517                  1                     1              1        2                    NaN                      23                    NaN                            0                     7              9               8           13        1         10            21            9                   10       0                0            0                  5                  100            37.5             0                    0         55800           25787             52500          0                          NaN             NaN                    NaN                     NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Cash                N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

In [3]:
url = 'Loan_joined.csv'
DF = pd.read_csv(url, delimiter = ',')

C:\Users\usuario\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (1,20,60,119,130,131,132,135,136,137,140,146,147,148) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

### Eliminate observations

In [18]:
DF = DF[DF.loan_status.isin(['Fully Paid', 'In Grace Period', 'Late (31-120 days)',
       'Late (16-30 days)', 'Charged Off', 'Default'])]
DF.shape, DF.loan_status.unique()

AttributeError: 'DataFrame' object has no attribute 'loan_status'

### Dummy convertion

In [5]:
DF['loan_acceptance'] = DF['loan_status'].map({'Fully Paid':1,
                                               'In Grace Period':0,
                                               'Late (31-120 days)':0,
                                               'Late (16-30 days)':0,
                                               'Charged Off':0,
                                               'Default':0})

print("Current shape of dataset :",DF.shape)

Current shape of dataset : (462191, 153)

### Dataframe list convertion

In [6]:
DF_UNO = DF[DF['application_type'] == 'Individual']

lista_ind = ['loan_acceptance','acc_now_delinq','acc_open_past_24mths','all_util','annual_inc','avg_cur_bal','bc_util',
             'collections_12_mths_ex_med','delinq_2yrs', 'delinq_amnt','dti','emp_length','home_ownership',
             'il_util','inq_fi','inq_last_12m','inq_last_6mths','installment','int_rate','loan_amnt','max_bal_bc',
             'mo_sin_old_il_acct','mo_sin_rcnt_rev_tl_op','mort_acc','mths_since_last_delinq',
             'mths_since_recent_bc_dlq','mths_since_recent_inq','mths_since_recent_revol_delinq',
             'num_actv_bc_tl','num_actv_rev_tl','num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl',
             'num_rev_accts','num_rev_tl_bal_gt_0','num_sats','num_tl_120dpd_2m','num_tl_30dpd',
             'num_tl_90g_dpd_24m','num_tl_op_past_12m','open_acc','open_act_il','percent_bc_gt_75','revol_bal',
             'tax_liens','tot_cur_bal','tot_hi_cred_lim','total_acc','total_bal_ex_mort','total_bal_il',
             'total_bc_limit','total_cu_tl','total_rev_hi_lim']
df_ind = DF_UNO[lista_ind]
df_ind.shape

(460541, 54)

### Variable engineering

#### emp_length

In [7]:
def años_casa(x):
    if x == '< 1 year':
        return '0'
    elif x == '1 year':
        return '1'
    elif x == '2 years':
        return '2'
    elif x == '3 years':
        return '3'
    elif x == '4 years':
        return '4'
    elif x == '5 years':
        return '5'
    elif x == '6 years':
        return '6'
    elif x == '7 years':
        return '7'
    elif x == '8 years':
        return '8'
    elif x == '9 years':
        return '9'
    elif x == '10+ years':
        return '10'
    else:
        return '0'
df_ind['emp_length'] = df_ind['emp_length'].map(años_casa)
df_ind['emp_length'] = pd.to_numeric(df_ind['emp_length'])

<ipython-input-7-3bf4cc268f21>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ind['emp_length'] = df_ind['emp_length'].map(años_casa)
<ipython-input-7-3bf4cc268f21>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ind['emp_length'] = pd.to_numeric(df_ind['emp_length'])

#### home_ownership

In [8]:
one_hot = pd.get_dummies(df_ind['home_ownership'])
one_hot = one_hot.drop('ANY', axis = 1)
one_hot.shape

(460541, 3)

In [9]:
df_ind = df_ind.drop(['home_ownership'], axis = 1)

In [10]:
df_ind = pd.concat([df_ind, one_hot], axis=1)

#### int_rate

In [11]:
df_ind['int_rate'] = list(map(lambda x : x[:-1], df_ind.int_rate))
df_ind['int_rate'] = pd.to_numeric(df_ind['int_rate'])

### Pipeline and scalation

In [12]:
lista_final = ['loan_acceptance','acc_now_delinq','acc_open_past_24mths','all_util','annual_inc','avg_cur_bal','bc_util',
             'collections_12_mths_ex_med','delinq_2yrs', 'delinq_amnt','dti','emp_length',
             'il_util','inq_fi','inq_last_12m','inq_last_6mths','int_rate','loan_amnt','max_bal_bc',
             'mo_sin_old_il_acct','mo_sin_rcnt_rev_tl_op','mort_acc','mths_since_last_delinq',
             'mths_since_recent_inq','num_actv_bc_tl','num_actv_rev_tl','num_bc_sats','num_bc_tl',
             'num_il_tl','num_op_rev_tl','num_rev_accts','num_tl_120dpd_2m','num_tl_30dpd',
             'num_tl_90g_dpd_24m','num_tl_op_past_12m','open_acc','open_act_il','percent_bc_gt_75',
             'revol_bal','tax_liens','tot_cur_bal','total_acc','total_bal_ex_mort',
             'total_bc_limit','total_cu_tl','total_rev_hi_lim','MORTGAGE', 'OWN', 'RENT']

df_ind = df_ind[lista_final]
df_ind.shape

(460541, 49)

## Y

In [13]:
loan_acceptance_df = df_ind['loan_acceptance']
loan_acceptance_df = pd.DataFrame(loan_acceptance_df)
loan_acceptance_df.reset_index(drop=True, inplace=True)
loan_acceptance_df.head(10)

   loan_acceptance
0                1
1                1
2                1
3                1
4                1
5                1
6                0
7                1
8                0
9                1

In [14]:
df_ind_xd = df_ind.drop(['loan_acceptance'], axis = 1)
df_ind_xd.reset_index(drop=True, inplace=True)
df_ind_xd.head()

,acc_now_delinq,acc_open_past_24mths,all_util,annual_inc,avg_cur_bal,bc_util,collections_12_mths_ex_med,delinq_2yrs,delinq_amnt,dti,...,tax_liens,tot_cur_bal,total_acc,total_bal_ex_mort,total_bc_limit,total_cu_tl,total_rev_hi_lim,MORTGAGE,OWN,RENT
0,0.0,8.0,36.0,153000.0,23302.0,13.6,0.0,0.0,0.0,16.99,...,0.0,442731.0,46.0,100865.0,28100.0,6.0,37600.0,0,1,0
1,0.0,2.0,74.0,50000.0,1863.0,98.9,0.0,0.0,0.0,6.07,...,0.0,5588.0,5.0,5588.0,3600.0,0.0,3600.0,0,0,1
2,0.0,13.0,39.0,110000.0,14551.0,27.9,0.0,0.0,0.0,13.12,...,0.0,276461.0,27.0,45955.0,83700.0,8.0,85700.0,1,0,0
3,0.0,7.0,32.0,51979.0,730.0,22.2,0.0,0.0,0.0,10.11,...,0.0,10956.0,21.0,10956.0,18800.0,0.0,28700.0,0,0,1
4,0.0,5.0,83.0,75000.0,31911.0,90.0,0.0,1.0,0.0,10.86,...,0.0,127645.0,10.0,27684.0,3000.0,0.0,3000.0,1,0,0

In [15]:
transformador_numerico = Pipeline(steps=[
    
    ('imputador', SimpleImputer(strategy = 'median')),
    
    ('escalador', StandardScaler())
    
])

In [16]:
df_ind_esc = transformador_numerico.fit_transform(df_ind_xd)
df_ind_esc = pd.DataFrame(df_ind_esc)

In [17]:
lista_ind_1 = ['acc_now_delinq','acc_open_past_24mths','all_util','annual_inc','avg_cur_bal','bc_util',
             'collections_12_mths_ex_med','delinq_2yrs', 'delinq_amnt','dti','emp_length',
             'il_util','inq_fi','inq_last_12m','inq_last_6mths','int_rate','loan_amnt','max_bal_bc',
             'mo_sin_old_il_acct','mo_sin_rcnt_rev_tl_op','mort_acc','mths_since_last_delinq',
             'mths_since_recent_inq',
             'num_actv_bc_tl','num_actv_rev_tl','num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl',
             'num_rev_accts','num_tl_120dpd_2m','num_tl_30dpd',
             'num_tl_90g_dpd_24m','num_tl_op_past_12m','open_acc','open_act_il','percent_bc_gt_75','revol_bal',
             'tax_liens','tot_cur_bal','total_acc','total_bal_ex_mort',
             'total_bc_limit','total_cu_tl','total_rev_hi_lim','MORTGAGE', 'OWN', 'RENT']
df_ind_esc.columns = [lista_ind_1]
df_ind_esc.head(10)

,acc_now_delinq,acc_open_past_24mths,all_util,annual_inc,avg_cur_bal,bc_util,collections_12_mths_ex_med,delinq_2yrs,delinq_amnt,dti,...,tax_liens,tot_cur_bal,total_acc,total_bal_ex_mort,total_bc_limit,total_cu_tl,total_rev_hi_lim,MORTGAGE,OWN,RENT
0,-0.070414,1.010683,-4.391856,1.169092,0.632931,-1.756350,-0.121123,-0.373769,-0.018151,-0.168370,...,-0.136687,1.966093,1.645054,1.082435,0.364780,6.494958,0.169542,-0.990665,2.932031,-0.817319
1,-0.070414,-0.889720,2.588767,-0.388652,-0.712121,1.344204,-0.121123,-0.373769,-0.018151,-1.473418,...,-0.136687,-0.865215,-1.726894,-0.937178,-0.813060,-1.373566,-0.787800,-0.990665,-0.341061,1.223512
2,-0.070414,2.594353,-3.840754,0.518772,0.083906,-1.236562,-0.121123,-0.373769,-0.018151,-0.630874,...,-0.136687,0.889188,0.082444,-0.081508,3.037755,9.117799,1.523901,1.009422,-0.341061,-0.817319
3,-0.070414,0.693949,-5.126658,-0.358722,-0.783204,-1.443750,-0.121123,-0.373769,-0.018151,-0.990598,...,-0.136687,-0.830447,-0.411012,-0.823391,-0.082319,-1.373566,-0.081056,-0.990665,-0.341061,1.223512
4,-0.070414,0.060482,4.242073,-0.010558,1.173048,1.020700,-0.121123,0.716465,-0.018151,-0.900966,...,-0.136687,-0.074671,-1.315681,-0.468803,-0.841905,-1.373566,-0.804695,1.009422,-0.341061,-0.817319
5,-0.070414,0.060482,-3.289652,1.274959,-0.699322,-0.883978,-0.121123,-0.373769,-0.018151,-1.351518,...,-0.136687,-0.727349,0.822627,-0.485973,0.283052,-1.373566,0.476455,1.009422,-0.341061,-0.817319
6,-0.070414,-0.256252,4.425773,-0.645755,-0.663749,1.246062,-0.121123,-0.373769,-0.018151,1.664912,...,-0.136687,-0.730795,-0.575497,-0.497250,-0.639990,-0.062145,-0.638568,-0.990665,-0.341061,1.223512
7,-0.070414,-0.889720,0.935462,-0.192043,1.385794,0.958907,-0.121123,-0.373769,-0.018151,-0.216174,...,-0.136687,1.156410,-0.739982,-0.331657,-0.563069,-1.373566,-0.345733,-0.990665,2.932031,-0.817319
8,-0.070414,-0.572986,7.364983,0.140679,-0.344724,1.384188,-0.121123,0.716465,-0.018151,-0.450414,...,-0.136687,-0.701416,-1.315681,-0.233810,-0.440478,2.560696,-0.569583,-0.990665,-0.341061,1.223512
9,-0.070414,-0.572986,0.016959,-0.570137,0.288371,-1.076627,-0.121123,0.716465,1.427641,0.024041,...,-0.136687,0.136760,-0.822225,-0.625303,-0.514994,-0.062145,-0.486519,1.009422,-0.341061,-0.817319

In [18]:
#Unimos datasets
df_ind_esc = pd.concat([loan_acceptance_df, df_ind_esc], axis = 1)
df_ind_esc.head(15)

,loan_acceptance,"(acc_now_delinq,)","(acc_open_past_24mths,)","(all_util,)","(annual_inc,)","(avg_cur_bal,)","(bc_util,)","(collections_12_mths_ex_med,)","(delinq_2yrs,)","(delinq_amnt,)",...,"(tax_liens,)","(tot_cur_bal,)","(total_acc,)","(total_bal_ex_mort,)","(total_bc_limit,)","(total_cu_tl,)","(total_rev_hi_lim,)","(MORTGAGE,)","(OWN,)","(RENT,)"
0,1,-0.070414,1.010683,-4.391856,1.169092,0.632931,-1.756350,-0.121123,-0.373769,-0.018151,...,-0.136687,1.966093,1.645054,1.082435,0.364780,6.494958,0.169542,-0.990665,2.932031,-0.817319
1,1,-0.070414,-0.889720,2.588767,-0.388652,-0.712121,1.344204,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.865215,-1.726894,-0.937178,-0.813060,-1.373566,-0.787800,-0.990665,-0.341061,1.223512
2,1,-0.070414,2.594353,-3.840754,0.518772,0.083906,-1.236562,-0.121123,-0.373769,-0.018151,...,-0.136687,0.889188,0.082444,-0.081508,3.037755,9.117799,1.523901,1.009422,-0.341061,-0.817319
3,1,-0.070414,0.693949,-5.126658,-0.358722,-0.783204,-1.443750,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.830447,-0.411012,-0.823391,-0.082319,-1.373566,-0.081056,-0.990665,-0.341061,1.223512
4,1,-0.070414,0.060482,4.242073,-0.010558,1.173048,1.020700,-0.121123,0.716465,-0.018151,...,-0.136687,-0.074671,-1.315681,-0.468803,-0.841905,-1.373566,-0.804695,1.009422,-0.341061,-0.817319
5,1,-0.070414,0.060482,-3.289652,1.274959,-0.699322,-0.883978,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.727349,0.822627,-0.485973,0.283052,-1.373566,0.476455,1.009422,-0.341061,-0.817319
6,0,-0.070414,-0.256252,4.425773,-0.645755,-0.663749,1.246062,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.730795,-0.575497,-0.497250,-0.639990,-0.062145,-0.638568,-0.990665,-0.341061,1.223512
7,1,-0.070414,-0.889720,0.935462,-0.192043,1.385794,0.958907,-0.121123,-0.373769,-0.018151,...,-0.136687,1.156410,-0.739982,-0.331657,-0.563069,-1.373566,-0.345733,-0.990665,2.932031,-0.817319
8,0,-0.070414,-0.572986,7.364983,0.140679,-0.344724,1.384188,-0.121123,0.716465,-0.018151,...,-0.136687,-0.701416,-1.315681,-0.233810,-0.440478,2.560696,-0.569583,-0.990665,-0.341061,1.223512
9,1,-0.070414,-0.572986,0.016959,-0.570137,0.288371,-1.076627,-0.121123,0.716465,1.427641,...,-0.136687,0.136760,-0.822225,-0.625303,-0.514994,-0.062145,-0.486519,1.009422,-0.341061,-0.817319
10,0,-0.070414,-1.206454,3.139869,-0.615508,-0.696373,1.235158,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.860338,-1.562408,-0.921217,-0.880365,1.249275,-0.827220,-0.990665,-0.341061,1.223512
11,1,-0.070414,-0.572986,-11.005077,2.636094,5.047091,-2.250694,-0.121123,0.716465,-0.018151,...,-0.136687,3.344930,0.658142,0.821729,2.715651,-0.062145,1.982862,1.009422,-0.341061,-0.817319
12,1,-0.070414,0.377215,2.405067,0.140679,0.502874,0.246470,-0.121123,-0.373769,-0.018151,...,-0.136687,0.748543,1.316083,1.727553,0.182094,1.249275,0.020309,1.009422,-0.341061,-0.817319
13,0,-0.070414,0.693949,4.425773,5.660840,3.497323,0.729909,-0.121123,-0.373769,-0.018151,...,-0.136687,5.351457,1.809539,3.158602,4.460777,-0.062145,6.707630,1.009422,-0.341061,-0.817319
14,1,-0.070414,0.060482,4.425773,-0.464270,0.527782,0.457293,-0.121123,-0.373769,-0.018151,...,-0.136687,0.779425,-0.493254,0.071515,-0.067896,-0.062145,-0.283788,1.009422,-0.341061,-0.817319

### Outliers treatment

In [19]:
for col in df_ind_esc.columns:
    percentiles = df_ind_esc[col].quantile([0.01,0.99]).values
    df_ind_esc[col] = np.clip(df_ind_esc[col], percentiles[0], percentiles[1])

### Guardado de Excel

In [25]:
#Dataframe escalado, sin valores nulos (cambiados por la mediana) y con 56 variables (PARA INDIVIDUAL)
df_ind_esc.head(5)

,loan_acceptance,"(acc_now_delinq,)","(acc_open_past_24mths,)","(all_util,)","(annual_inc,)","(avg_cur_bal,)","(bc_util,)","(collections_12_mths_ex_med,)","(delinq_2yrs,)","(delinq_amnt,)",...,"(tax_liens,)","(tot_cur_bal,)","(total_acc,)","(total_bal_ex_mort,)","(total_bc_limit,)","(total_cu_tl,)","(total_rev_hi_lim,)","(MORTGAGE,)","(OWN,)","(RENT,)"
0,1,-0.070414,1.010683,-4.391856,1.169092,0.632931,-1.756350,-0.121123,-0.373769,-0.018151,...,-0.136687,1.966093,1.645054,1.082435,0.364780,3.872116,0.169542,-0.990665,2.932031,-0.817319
1,1,-0.070414,-0.889720,2.588767,-0.388652,-0.712121,1.344204,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.865215,-1.644651,-0.937178,-0.813060,-1.373566,-0.787800,-0.990665,-0.341061,1.223512
2,1,-0.070414,2.594353,-3.840754,0.518772,0.083906,-1.236562,-0.121123,-0.373769,-0.018151,...,-0.136687,0.889188,0.082444,-0.081508,3.037755,3.872116,1.523901,1.009422,-0.341061,-0.817319
3,1,-0.070414,0.693949,-4.391856,-0.358722,-0.783204,-1.443750,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.830447,-0.411012,-0.823391,-0.082319,-1.373566,-0.081056,-0.990665,-0.341061,1.223512
4,1,-0.070414,0.060482,3.690971,-0.010558,1.173048,1.020700,-0.121123,0.716465,-0.018151,...,-0.136687,-0.074671,-1.315681,-0.468803,-0.841905,-1.373566,-0.804695,1.009422,-0.341061,-0.817319

In [ ]:
df_ind_esc.to_csv('PRUEBA.csv') #index = false

## Importamos de nuevo la BB.DD

In [26]:
url = 'PRUEBA.csv'
new_df = pd.read_csv(url, delimiter = ',')

In [27]:
new_df.head(5)

,Unnamed: 0,loan_acceptance,"('acc_now_delinq',)","('acc_open_past_24mths',)","('all_util',)","('annual_inc',)","('avg_cur_bal',)","('bc_util',)","('collections_12_mths_ex_med',)","('delinq_2yrs',)",...,"('tax_liens',)","('tot_cur_bal',)","('total_acc',)","('total_bal_ex_mort',)","('total_bc_limit',)","('total_cu_tl',)","('total_rev_hi_lim',)","('MORTGAGE',)","('OWN',)","('RENT',)"
0,0,1,-0.070414,1.010683,-4.391856,1.169092,0.632931,-1.756350,-0.121123,-0.373769,...,-0.136687,1.966093,1.645054,1.082435,0.364780,3.872116,0.169542,-0.990665,2.932031,-0.817319
1,1,1,-0.070414,-0.889720,2.588767,-0.388652,-0.712121,1.344204,-0.121123,-0.373769,...,-0.136687,-0.865215,-1.644651,-0.937178,-0.813060,-1.373566,-0.787800,-0.990665,-0.341061,1.223512
2,2,1,-0.070414,2.594353,-3.840754,0.518772,0.083906,-1.236562,-0.121123,-0.373769,...,-0.136687,0.889188,0.082444,-0.081508,3.037755,3.872116,1.523901,1.009422,-0.341061,-0.817319
3,3,1,-0.070414,0.693949,-4.391856,-0.358722,-0.783204,-1.443750,-0.121123,-0.373769,...,-0.136687,-0.830447,-0.411012,-0.823391,-0.082319,-1.373566,-0.081056,-0.990665,-0.341061,1.223512
4,4,1,-0.070414,0.060482,3.690971,-0.010558,1.173048,1.020700,-0.121123,0.716465,...,-0.136687,-0.074671,-1.315681,-0.468803,-0.841905,-1.373566,-0.804695,1.009422,-0.341061,-0.817319

In [28]:
new_df = new_df.iloc[:,1:50]

In [29]:
new_df.head(5)

,loan_acceptance,"('acc_now_delinq',)","('acc_open_past_24mths',)","('all_util',)","('annual_inc',)","('avg_cur_bal',)","('bc_util',)","('collections_12_mths_ex_med',)","('delinq_2yrs',)","('delinq_amnt',)",...,"('tax_liens',)","('tot_cur_bal',)","('total_acc',)","('total_bal_ex_mort',)","('total_bc_limit',)","('total_cu_tl',)","('total_rev_hi_lim',)","('MORTGAGE',)","('OWN',)","('RENT',)"
0,1,-0.070414,1.010683,-4.391856,1.169092,0.632931,-1.756350,-0.121123,-0.373769,-0.018151,...,-0.136687,1.966093,1.645054,1.082435,0.364780,3.872116,0.169542,-0.990665,2.932031,-0.817319
1,1,-0.070414,-0.889720,2.588767,-0.388652,-0.712121,1.344204,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.865215,-1.644651,-0.937178,-0.813060,-1.373566,-0.787800,-0.990665,-0.341061,1.223512
2,1,-0.070414,2.594353,-3.840754,0.518772,0.083906,-1.236562,-0.121123,-0.373769,-0.018151,...,-0.136687,0.889188,0.082444,-0.081508,3.037755,3.872116,1.523901,1.009422,-0.341061,-0.817319
3,1,-0.070414,0.693949,-4.391856,-0.358722,-0.783204,-1.443750,-0.121123,-0.373769,-0.018151,...,-0.136687,-0.830447,-0.411012,-0.823391,-0.082319,-1.373566,-0.081056,-0.990665,-0.341061,1.223512
4,1,-0.070414,0.060482,3.690971,-0.010558,1.173048,1.020700,-0.121123,0.716465,-0.018151,...,-0.136687,-0.074671,-1.315681,-0.468803,-0.841905,-1.373566,-0.804695,1.009422,-0.341061,-0.817319

In [30]:
new_df.shape

(460541, 49)